#Properties usadas en el registro del conector
connector.code = 77520672
connector.contextpath = wu-connector-cashin-pago-efectivo-online/rest
connector.nombre = Conector wu-connector-cashin-pago-efectivo-online
connector.descripcion = Conector wu-connector-cashin-pago-efectivo-online
connector.parameters = client.url.consulta, client.url.directa, client.url.reversa, client.useragent, client.url.token, client.tokenUser, client.tokenPass, client.tokenGrantType, client.connectionTimeout, client.user, client.pass, recarga.con.barra, client.key, client.keyType 


#Properties usadas en el registro del conector como parametros del conector
client.url.consulta.required = true
client.url.consulta.prompt = Endpoint Consulta(*)
client.url.consulta.value = http://10.221.0.10:8220/v1/payments/WEU/cips

client.url.directa.required = true
client.url.directa.prompt = Endpoint Directa(*)
client.url.directa.value = http://10.221.0.10:8220/v1/payments/WEU/payment

client.url.reversa.required = false
client.url.reversa.prompt = Endpoint Reversa
client.url.reversa.value = http://10.221.0.10:8220/v1/payments/WEU/refunds/

client.agreement.code.required = true
client.agreement.code.prompt = Codigo que identifica el producto
client.agreement.code.value = 0006

client.channel.required = true
client.channel.prompt = Descripcion del canal de envio
client.channel.value = 2

client.secret.key.required = true
client.secret.key.prompt = Llave de seguridad por transaccion
client.secret.key.value = ce695f7c-ccac-4562-8626-2f20bf5634d0

client.user.required=true
client.user.prompt=Usuario(*)
client.user.value=pagofacil

client.pass.required=true
client.pass.prompt=Contrasena(*)
client.pass.value=pagofacil
####################################################
client.useragent.required = false
client.useragent.prompt = User Agent
client.useragent.value =

client.tokenGrantType.required = false
client.tokenGrantType.prompt = Permiso/palabra (campo para generar token)
client.tokenGrantType.value =

client.key.required = false
client.key.prompt = token/api-key
client.key.value =

client.keyType.required = false
client.keyType.prompt = Tipo de token/api-key
client.keyType.value =

client.connectionTimeout.required = true
client.connectionTimeout.prompt = Timeout para creacion de proxy(*)
client.connectionTimeout.value = 18000 

recarga.con.barra.required = true
recarga.con.barra.prompt = Recarga con barra(*)
recarga.con.barra.value = O
####################################################

requestEcho.json.file.path = requestEcho.json